export const MENUITEMS = [
  {
    Items: [
      {
        path: `/dashboard`,
        icon: "si si-people",
        type: "link",
        active: false,
        selected: false,
        title: "Dashboard",
      },
      {
        path: `/blog`,
        icon: "si si-people",
        type: "link",
        active: false,
        selected: false,
        title: "Blog",
      },
      {
        path: `/broker`,
        icon: "ti-bookmark-alt",
        type: "link",
        active: false,
        selected: false,
        title: "Broker",
      },
      {
        path: `/mutual`,
        icon: "ti-bookmark-alt",
        type: "link",
        active: false,
        selected: false,
        title: "Mutual fund",
      },
      {
        path: `/learning`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Learning",
      },
      {
        path: `/commodity`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Commidity",
      },
      {
        path: `/intraday`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Intraday",
      },
      {
        path: `/fostocks`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "FoStocks",
      },
      {
        path: `/yearly`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Yearly",
      },
      {
        path: `/monthly`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Monthly",
      },
      {
        path: `/weekly`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Weekly",
      },
      {
        path: `/daily`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Daily",
      },
      {
        path: `/notification`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Notification",
      },
      {
        path: `/setting`,
        icon: "ti-filter",
        type: "link",
        active: false,
        selected: false,
        title: "Setting",
      },
    ],
  },
];
